server:
  port: 3000

spring:
  application:
    name: xiaowu-crowd-redis
  redis:
   host: 127.0.0.1
   port: 6379
   database: 0
   password:
   lettuce:
     pool:
       max-active: 20
       max-wait: -1
       max-idle: 8
       min-idle: 0